language: python
python:
  - "3.6.7"
# command to install dependencies
services:
  - postgresql
cache: pip
install: 
  - pip install -r requirements.txt
before_script:
# command to run tests
  - psql -c "CREATE DATABASE elise_db;" -U postgres
  - psql -c "CREATE USER elise WITH PASSWORD 'elise1*';" -U postgres
script: 
  - py.test
after_success:

deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: "f47bb072-c8c0-45e9-87d7-7cc2d76a9b4d"
  strategy: git
  app: gobulk
  on:
    branch: release