"""empty message

Revision ID: 111ae1fc843e
Revises: aa616e6eb899
Create Date: 2019-04-27 04:36:08.344520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '111ae1fc843e'
down_revision = 'aa616e6eb899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'modified_at')
    op.add_column('messages', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.drop_column('messages', 'created_at')
    op.add_column('projects', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'modified_at')
    op.add_column('projectslog', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('projectslog', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.drop_column('projectslog', 'created_at')
    op.drop_column('projectslog', 'modified_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectslog', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projectslog', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('projectslog', 'modified_on')
    op.drop_column('projectslog', 'created_on')
    op.add_column('projects', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'modified_on')
    op.drop_column('projects', 'created_on')
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'modified_on')
    op.drop_column('messages', 'created_on')
    op.add_column('groups', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('groups', 'modified_on')
    op.drop_column('groups', 'created_on')
    # ### end Alembic commands ###
