"""empty message

Revision ID: 1edb737cb4c8
Revises: 1ea09de7a32a
Create Date: 2019-04-28 18:36:10.923712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edb737cb4c8'
down_revision = '1ea09de7a32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'supervisor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'supervisor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
