"""empty message

Revision ID: 3b52ec217d5c
Revises: 477cd18a5fa8
Create Date: 2019-05-29 03:05:03.622388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b52ec217d5c'
down_revision = '477cd18a5fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectslog', sa.Column('group_id', sa.String(), nullable=False))
    op.add_column('projectslog', sa.Column('supervisor_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'projectslog', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'projectslog', 'supervisors', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projectslog', type_='foreignkey')
    op.drop_constraint(None, 'projectslog', type_='foreignkey')
    op.drop_column('projectslog', 'supervisor_id')
    op.drop_column('projectslog', 'group_id')
    # ### end Alembic commands ###
