"""empty message

Revision ID: 502faf439705
Revises: a5884d200906
Create Date: 2019-05-01 14:02:16.651482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502faf439705'
down_revision = 'a5884d200906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phonenumber', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('user_role_name', sa.String(length=128), nullable=False),
    sa.Column('user_role_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('groups', sa.Column('password', sa.String(length=128), nullable=False))
    op.alter_column('groups', 'number',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint(None, 'groups', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.alter_column('groups', 'number',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('groups', 'password')
    op.drop_table('admins')
    # ### end Alembic commands ###
