"""empty message

Revision ID: 546ec3aa0e9b
Revises: 5def51842e7f
Create Date: 2019-06-05 12:37:43.592654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546ec3aa0e9b'
down_revision = '5def51842e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectslog', sa.Column('week', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectslog', 'week')
    # ### end Alembic commands ###
