"""empty message

Revision ID: 91b30dd39d09
Revises: 546ec3aa0e9b
Create Date: 2019-06-05 14:47:31.904632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b30dd39d09'
down_revision = '546ec3aa0e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('subject', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'subject')
    # ### end Alembic commands ###
