"""empty message

Revision ID: 9b9e61cfeda4
Revises: efa92c9f4204
Create Date: 2019-05-17 10:17:38.141814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9e61cfeda4'
down_revision = 'efa92c9f4204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_created_by_key', 'groups', type_='unique')
    op.add_column('projects', sa.Column('created_by', sa.String(length=128), nullable=False))
    op.add_column('projects', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'created_by')
    op.create_unique_constraint('groups_created_by_key', 'groups', ['created_by'])
    # ### end Alembic commands ###
