"""empty message

Revision ID: a5884d200906
Revises: 1edb737cb4c8
Create Date: 2019-04-29 15:12:52.525653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5884d200906'
down_revision = '1edb737cb4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_phonenumber_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['student_number'])
    op.drop_constraint('supervisors_phonenumber_key', 'supervisors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('supervisors_phonenumber_key', 'supervisors', ['phonenumber'])
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_phonenumber_key', 'students', ['phonenumber'])
    # ### end Alembic commands ###
