"""empty message

Revision ID: aa616e6eb899
Revises: 92a06a3bfb0a
Create Date: 2019-04-27 04:13:10.148732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa616e6eb899'
down_revision = '92a06a3bfb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('students', sa.Column('user_role_name', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('user_role_value', sa.Integer(), nullable=False))
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'modified_at')
    op.add_column('supervisors', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('supervisors', sa.Column('modified_on', sa.DateTime(), nullable=True))
    op.add_column('supervisors', sa.Column('user_role_name', sa.Integer(), nullable=False))
    op.add_column('supervisors', sa.Column('user_role_value', sa.Integer(), nullable=False))
    op.drop_column('supervisors', 'created_at')
    op.drop_column('supervisors', 'modified_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supervisors', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('supervisors', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('supervisors', 'user_role_value')
    op.drop_column('supervisors', 'user_role_name')
    op.drop_column('supervisors', 'modified_on')
    op.drop_column('supervisors', 'created_on')
    op.add_column('students', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('students', 'user_role_value')
    op.drop_column('students', 'user_role_name')
    op.drop_column('students', 'title')
    op.drop_column('students', 'modified_on')
    op.drop_column('students', 'created_on')
    # ### end Alembic commands ###
