"""empty message

Revision ID: efa92c9f4204
Revises: ff3695e1d2a0
Create Date: 2019-05-16 15:48:58.020290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa92c9f4204'
down_revision = 'ff3695e1d2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'groups', ['created_by'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_column('groups', 'created_by')
    # ### end Alembic commands ###
