"""empty message

Revision ID: ff3695e1d2a0
Revises: 502faf439705
Create Date: 2019-05-16 15:36:35.319858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3695e1d2a0'
down_revision = '502faf439705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
